#import "../template.typ": *
#import "@preview/fletcher:0.5.8": *
#import "@preview/cetz:0.5.2"

#show: doc => conf(
  easy: true,
  doc,
)

= Dedekind Domains

This chapter follows a local-to-global path. A DVR is the one-prime local
model; a Dedekind domain is the global ring obtained by requiring this model
at every nonzero prime. Fractional ideals then assemble the local valuations
into global prime factorizations, divisors, and finally the class group.

== Discrete Valuation Rings

The word #emph[discrete] means that divisibility is measured by integers. A discrete
valuation turns multiplication in a field into addition in $ZZ$, so the order
of a zero or a pole becomes an ordinary integer.

#definition(title: "Discrete Valuation")[
  Let $K$ be a field. A #emph[discrete valuation] on $K$ is a surjective group
  homomorphism

  $ v: K^times -> ZZ $

  such that

  $ v(x+y) >= min(v(x),v(y)) $

  whenever $x,y in K^times$ and $x+y != 0$. We extend $v$ to all of $K$ by
  setting $v(0)=+infinity$.
]

#definition(title: "Discrete Valuation Ring")[
  Let $v$ be a discrete valuation on $K$. Its #emph[valuation ring] is

  $ cal(O)_v := {x in K | v(x) >= 0} $

  A domain $A$ is a #emph[discrete valuation ring], abbreviated #emph[DVR], if its
  fraction field is $K$ and $A=cal(O)_v$ for some discrete valuation $v$ on
  $K$.
]

The ring $cal(O)_v$ is local. Its unique maximal ideal, its group of units, and
its residue field are respectively

$ frak(m)_v={x in K | v(x)>0}, quad cal(O)_v^times={x in K | v(x)=0}, quad kappa(v)=cal(O)_v slash frak(m)_v $

Since $v$ is surjective, there is an element $pi in K$ with $v(pi)=1$. Such an
element automatically lies in $cal(O)_v$ and generates $frak(m)_v$; it is
called a #emph[uniformizer] (or a #emph[prime element]). A uniformizer is not unique, but
any two uniformizers differ by a unit.

#remark(title: "What a DVR remembers")[
  Fix a uniformizer $pi$. Every $x in K^times$ has a unique expression

  $ x=u pi^n, quad u in A^times, quad n in ZZ $

  and $n=v(x)$. Thus $v(x)=0$ means that $x$ is a unit, $v(x)>0$ records the
  order to which $x$ vanishes, and $v(x)<0$ records the order of its pole.
  Moreover, for nonzero $x,y in A$,

  $ x divides y <=> v(x) <= v(y) $

  In this sense a DVR is a one-dimensional local ring with only one direction
  of vanishing. Geometrically, the local ring of an integral curve at a regular
  closed point is a DVR, and its valuation is the order of vanishing at that
  point.
]

#theorem(title: "Equivalent characterizations of a DVR")[
  Let $A$ be a domain that is not a field, and let $K$ be its fraction field.
  The following conditions are equivalent.

  + $A$ is a DVR.

  + $A$ is a Noetherian valuation ring of $K$; equivalently, $A$ is Noetherian
    and for every $x in K^times$, either $x in A$ or $x^(-1) in A$.

  + $A$ is a principal ideal domain with exactly one nonzero prime ideal.

  + $A$ is a Noetherian local domain whose maximal ideal $frak(m)$ is generated
    by one nonzero element.

  + $A$ is a regular local ring of Krull dimension one. Equivalently, $A$ is
    Noetherian and local, $dim(A)=1$, and

    $ dim_(A slash frak(m)) (frak(m) slash frak(m)^2)=1 $

  + $A$ is a Noetherian normal local domain of Krull dimension one.

  + There is a nonzero element $pi in A$ such that every $x in K^times$ can be
    written uniquely as

    $ x=u pi^n, quad u in A^times, quad n in ZZ $

  + $A$ is local with maximal ideal $frak(m)$, and its nonzero ideals are
    precisely

    $ A=frak(m)^0, frak(m), frak(m)^2, frak(m)^3, dots $

    with no repetitions.
]

#proof[
  Suppose first that $A=cal(O)_v$ and choose $pi$ with $v(pi)=1$. For each
  $x in K^times$, the element $u=x pi^(-v(x))$ has valuation zero, hence is a
  unit of $A$. This gives the unique factorization $x=u pi^(v(x))$.

  Now let $I$ be a nonzero ideal of $A$. The set of valuations of its nonzero
  elements is a nonempty subset of $ZZ_(>=0)$, so it has a least element
  $n$. An element of valuation $n$ generates $I$, and therefore

  $ I=(pi^n)=frak(m)^n $

  Consequently all nonzero ideals are powers of $frak(m)=(pi)$, $A$ is a PID,
  and $frak(m)$ is its only nonzero prime ideal.

  Conversely, if $A$ is local and Noetherian with $frak(m)=(pi)$, the Krull
  intersection theorem gives $inter.big_(n>=0) frak(m)^n=(0)$. Repeatedly
  dividing a nonzero element by $pi$ must therefore stop, and every nonzero
  element of $A$ has the form $u pi^n$ with $u$ a unit. Extending the exponent
  to quotients defines a discrete valuation on $K$, with valuation ring exactly
  $A$.

  The factorization description makes the principal ideals of $A$ linearly
  ordered, so $A$ is a valuation ring. Conversely, every finitely generated
  ideal in a valuation ring is generated by an element of least valuation.
  Thus a Noetherian valuation ring that is not a field is a DVR.

  A DVR has only the prime ideals $(0)$ and $frak(m)$, so it has dimension one.
  It is also normal: if $x in K$ had $v(x)<0$, then in any monic equation for
  $x$ over $A$, the leading term would have strictly smaller valuation than all
  the other terms, which is impossible.

  Conversely, suppose that $A$ is Noetherian, normal, local, and
  one-dimensional. Choose $0 != a in frak(m)$. Since $frak(m)$ is the only
  prime ideal containing $(a)$, some power of $frak(m)$ lies in $(a)$. Choose
  $n$ minimal with $frak(m)^n subset.eq (a)$, take
  $y in frak(m)^(n-1) without (a)$, and put $z=y/a in K$. Then
  $z frak(m) subset.eq A$. If $z frak(m) subset.eq frak(m)$, the determinant
  trick would make $z$ integral over $A$, contradicting normality and
  $z in.not A$. Hence $z b$ is a unit for some $b in frak(m)$. For every
  $c in frak(m)$,

  $ c/b=(z c)/(z b) in A $

  so $frak(m)=(b)$. This recovers the principal maximal ideal criterion.
  Finally, Nakayama's lemma says that the minimal number of generators of
  $frak(m)$ is $dim_(A slash frak(m)) (frak(m) slash frak(m)^2)$, which gives
  the regular local characterization.
]

#example(title: "The basic examples")[
  Let $k$ be a field. The formal power series ring $k[[t]]$ is a DVR with
  uniformizer $t$. For a nonzero series $f=sum_(i>=0) a_i t^i$, its valuation
  is the least index $i$ for which $a_i != 0$.

  The localization $k[t]_((t))$ is also a DVR with uniformizer $t$. It consists
  of rational functions that are regular at $t=0$, and its valuation measures
  the order of vanishing at the origin.

  Similarly, for a prime number $p$, the local ring $ZZ_((p))$ is a DVR with
  fraction field $QQ$, uniformizer $p$, and residue field $FF_p$.
]

#example(title: "A nearby non-example")[
  The local ring $k[x,y]_((x,y))$ is not a DVR. Its maximal ideal $(x,y)$ needs
  two generators, and the ring has Krull dimension two. There are two
  independent directions of vanishing rather than one.
]

== Dedekind Domains: Definitions

A Dedekind domain can be recognized either from its global ring-theoretic
properties or from its local rings at nonzero prime ideals.

#definition(title: "Dedekind Domain")[
  Let $A$ be a domain that is not a field, and let $K$ be its fraction field.
  The following conditions are equivalent.

  + The ring $A$ is Noetherian, normal, and of Krull dimension one. Here
    #emph[normal] means that $A$ is integrally closed in $K$.

  + The ring $A$ is Noetherian, and for every nonzero prime ideal $frak(p)$ of
    $A$, the localization $A_(frak(p))$ is a DVR.

  A domain satisfying either condition is called a #emph[Dedekind domain].
]

#proof[
  Suppose first that $A$ is Noetherian, normal, and one-dimensional. Every
  nonzero prime ideal $frak(p)$ is maximal. Localization preserves both the
  Noetherian and normal properties, and

  $ dim(A_(frak(p)))="ht"(frak(p))=1 $

  Thus $A_(frak(p))$ is a Noetherian normal local domain of dimension one, so
  it is a DVR by the equivalent characterizations in the previous section.

  Conversely, suppose that $A$ is Noetherian and that $A_(frak(p))$ is a DVR
  for every nonzero prime $frak(p)$. We first show that $A$ is one-dimensional.
  If

  $ (0) subset frak(p) subset.eq frak(q) $

  is a chain of prime ideals, then after localization at $frak(q)$, the ideal
  $frak(p) A_(frak(q))$ is a nonzero prime ideal of the DVR
  $A_(frak(q))$. A DVR has only one nonzero prime ideal, so
  $frak(p) A_(frak(q))=frak(q) A_(frak(q))$. Contracting back to $A$ gives
  $frak(p)=frak(q)$. Hence every nonzero prime ideal is maximal and
  $dim(A)=1$.

  It remains to prove normality. Let $z in K$ be integral over $A$. Integrality
  is preserved by localization, so $z$ is integral over $A_(frak(m))$ for
  every maximal ideal $frak(m)$. Since $A$ is not a field, each maximal ideal is
  nonzero; hence every $A_(frak(m))$ is a DVR and is integrally closed. It
  follows that $z in A_(frak(m))$ for every maximal ideal $frak(m)$.

  A domain is the intersection of its localizations at all maximal ideals
  inside its fraction field. Indeed, if $z in.not A$, then

  $ I={a in A | a z in A} $

  is a proper ideal. Choose a maximal ideal $frak(m)$ containing $I$. If
  $z in A_(frak(m))$, then $s z in A$ for some $s in.not frak(m)$, which
  would give $s in I subset.eq frak(m)$, a contradiction. Therefore
  $z in A$, and $A$ is normal.
]

#remark[
  Some authors allow a field to be a Dedekind domain and replace
  $dim(A)=1$ by $dim(A)<=1$. In these notes a Dedekind domain is not a field, so
  the dimension is exactly one.
]

== Fractional Ideals and Prime Factorization

Let $A$ be a Dedekind domain with fraction field $K$. Ordinary ideals live
inside $A$, but taking an inverse usually introduces denominators. Fractional
ideals enlarge the collection of ideals just enough to make ideal
multiplication into a group operation.

#definition(title: "Fractional Ideal")[
  A #emph[fractional ideal] of $A$ is a nonzero $A$-submodule $I subset.eq K$
  for which there exists $0 != d in A$ such that

  $ d I subset.eq A $

  It is #emph[integral] if $I subset.eq A$, and #emph[principal] if
  $I=x A$ for some $x in K^times$. We also write $(x)=x A$.
]

#proposition(title: "Clearing Denominators")[
  Every fractional ideal $L$ can be written as

  $ L=1/a I $

  for some $0 != a in A$ and some nonzero integral ideal $I subset.eq A$.
  Conversely, every module of this form is a fractional ideal.
]

#proof[
  Choose $0 != a in A$ such that $a L subset.eq A$, and set $I=a L$. Then $I$
  is a nonzero integral ideal and $L=1/a I$. Conversely, if $I subset.eq A$ is
  a nonzero ideal, then $a(1/a I)=I subset.eq A$, so $1/a I$ satisfies the
  definition of a fractional ideal.
]

Thus a fractional ideal is simply an ordinary ideal with one common
denominator. Since $A$ is Noetherian, it is also a finitely generated
$A$-module.

#remark(title: "Why introduce denominators?")[
  An integral ideal can have an inverse only when it is the unit ideal: if
  $I subset.eq frak(m)$ is proper and $J subset.eq A$, then
  $I J subset.eq frak(m)$, so $I J != A$. Allowing submodules of $K$ makes room
  for negative orders of vanishing. Fractional ideals therefore play the same
  role for ideals that negative exponents play for numbers.
]

=== Ideal Operations

#definition(title: "Sum, Product, and Inverse")[
  For nonzero fractional ideals $I,J subset.eq K$, define their sum and product
  by

  $ I+J={x+y | x in I, y in J} $

  $ I J={sum_(i=1)^n x_i y_i | n>=1, x_i in I, y_i in J} $

  The inverse candidate of $I$ is the ideal quotient

  $ I^(-1)=(A:I):={x in K | x I subset.eq A} $

  Their intersection $I inter J$ is again a nonzero fractional ideal.
]

The finite sums in the definition of $I J$ are essential: the set of single
products $x y$ need not be closed under addition. With this definition,
multiplication is associative and commutative, distributes over sums, and has
identity $A$. Principal fractional ideals behave exactly as expected:

$ (x)(y)=(x y), quad (x)^(-1)=(x^(-1)) $

#theorem(title: "Invertibility and Unique Prime-Ideal Factorization")[
  Every nonzero fractional ideal $I$ of $A$ is invertible:

  $ I I^(-1)=A $

  For each nonzero prime ideal $frak(p)$, there is a unique integer
  $v_(frak(p)) (I)$ such that

  $ I A_(frak(p))=(frak(p) A_(frak(p)))^(v_(frak(p)) (I)) $

  Only finitely many of these integers are nonzero, and

  $ I=product_frak(p) frak(p)^(v_(frak(p)) (I)) $

  Consequently, the nonzero fractional ideals form an abelian group under
  ideal multiplication. They are also finite projective $A$-modules of rank
  one.
]

#proof[
  The localization $A_(frak(p))$ is a DVR. A finitely generated fractional
  ideal over a DVR is generated by an element of least valuation, so it is a
  unique integer power of the maximal ideal. This defines
  $v_(frak(p)) (I)$.

  The inverse candidate is itself fractional. Indeed, the denominator-clearing
  element $d$ belongs to $I^(-1)$, while any $0 != x in I$ gives
  $I^(-1) subset.eq x^(-1)A$.

  The equality
  $(I^(-1)) A_(frak(p))=(I A_(frak(p)))^(-1)$ holds because $I$ is finitely
  generated. Hence

  $ (I I^(-1)) A_(frak(p))=A_(frak(p)) $

  for every maximal ideal $frak(p)$. Equality of fractional ideals can be
  checked after localization at all maximal ideals, so $I I^(-1)=A$.

  Choose $0 != d in A$ with $d I subset.eq A$. The exponent
  $v_(frak(p)) (I)$ can be nonzero only if $frak(p)$ contains $d I$ or $(d)$.
  In a one-dimensional Noetherian domain, only finitely many prime ideals
  contain a fixed nonzero ideal. Thus the displayed product is finite and
  defines a fractional ideal $J$. At every $frak(p)$, the ideals $I$ and $J$
  have the same localization, so $I=J$. Uniqueness follows by localizing a
  proposed factorization at each $frak(p)$.

  Finally, an invertible ideal is locally free of rank one, hence finite
  projective of rank one.
]

#remark(title: "Why the Dedekind Hypotheses Matter")[
  The argument is local-to-global. The DVR condition produces one integer
  exponent at each nonzero prime, Noetherianity makes the support finite, and
  invertibility permits negative exponents and cancellation. Consequently,
  prime-ideal factorization survives even when factorization of elements does
  not.
]

#corollary(title: "The Exponent Dictionary")[
  For nonzero fractional ideals $I$ and $J$ and every nonzero prime
  $frak(p)$,

  #align(center, table(
    columns: (0.9fr, 1.5fr),
    align: (center, center),
    inset: (x: 12pt, y: 5.5pt),
    stroke: none,
    table.header(
      table.cell(align: center)[#text(fill: c-thm, weight: "bold")[Operation]],
      table.cell(align: center)[#text(fill: c-thm, weight: "bold")[Rule at $frak(p)$]],
    ),
    table.hline(stroke: 0.75pt + c-thm),
    table.vline(x: 1, stroke: 0.75pt + c-thm),
    [$I J$], [$v_(frak(p)) (I J)=v_(frak(p)) (I)+v_(frak(p)) (J)$],
    [$I^(-1)$], [$v_(frak(p)) (I^(-1))=-v_(frak(p)) (I)$],
    [$I+J$], [$v_(frak(p)) (I+J)=min(v_(frak(p)) (I),v_(frak(p)) (J))$],
    [$I inter J$], [$v_(frak(p)) (I inter J)=max(v_(frak(p)) (I),v_(frak(p)) (J))$],
  ))

  Moreover,

  $ I subset.eq J <=> v_(frak(p)) (I)>=v_(frak(p)) (J) " for every " frak(p) $

  The ideal $I$ is integral if and only if every $v_(frak(p)) (I)$ is
  nonnegative. For integral ideals, divisibility reverses containment:

  $ I " divides " J <=> J subset.eq I $
]

#proof[
  All statements may be checked after localization at $frak(p)$. In a DVR,
  powers of the maximal ideal satisfy

  $ frak(m)^a frak(m)^b=frak(m)^(a+b), quad frak(m)^a+frak(m)^b=frak(m)^(min(a,b)), quad frak(m)^a inter frak(m)^b=frak(m)^(max(a,b)) $

  The formulas and the reversed inequality for containment follow immediately.
  If $J=I L$ with $L$ integral, then the exponent of every prime in $J$ is at
  least its exponent in $I$, and conversely $L=J I^(-1)$ is integral whenever
  $J subset.eq I$.
]

#remark[
  The sum $I+J$ is the ideal-theoretic analogue of a greatest common divisor,
  while $I inter J$ behaves like a least common multiple. The reversal comes
  from $(a) subset.eq (b)$ precisely when $b$ divides $a$.
]

== Arithmetic of Integral Ideals

The prime exponents introduced for fractional ideals turn containment,
divisibility, coprimality, and congruences into elementary integer arithmetic.
We now collect the computational consequences used later in algebraic number
theory.

=== Exponents and Divisibility

#proposition(title: "Computing the Prime Exponents")[
  If $I$ is a nonzero integral ideal, then the exponent of a nonzero prime
  $frak(p)$ in its factorization is

  $ v_(frak(p)) (I)=max{n>=0 | I subset.eq frak(p)^n} $

  It can also be read locally as

  $ v_(frak(p)) (I)="length"_(A_(frak(p))) (A_(frak(p)) slash I A_(frak(p))) $

  In particular,

  $ v_(frak(p)) (I)>0 <=> I subset.eq frak(p) $

  Thus the prime ideals occurring in the factorization of $I$ are exactly the
  prime ideals containing $I$.
]

#proof[
  Localizing the factorization of $I$ at $frak(p)$ turns every prime factor
  other than $frak(p)$ into the unit ideal, so

  $ I A_(frak(p))=(frak(p) A_(frak(p)))^(v_(frak(p)) (I))=(pi^(v_(frak(p)) (I))) $

  The containment criterion in a DVR gives the maximum formula. The quotient
  of a DVR by $(pi^n)$ has length $n$, which gives the second formula. The last
  equivalence is the case $n=1$.
]

#remark(title: "The gcd and lcm Viewpoint")[
  These names have the same divisibility meaning as they do for integers.
  Recall that $D$ divides $I$ precisely when $I subset.eq D$. Therefore:

  + an ideal $D$ divides both $I$ and $J$ if and only if it divides
    $I+J="gcd"(I,J)$;

  + both $I$ and $J$ divide an ideal $M$ if and only if
    $I inter J="lcm"(I,J)$ divides $M$.

  The apparently reversed operations come from the reversed divisibility
  order on ideals. For example, in $ZZ$,

  $ (a)+(b)=("gcd"(a,b)), quad (a) inter (b)=("lcm"(a,b)) $

  In a general Dedekind domain the ideals $I+J$ and $I inter J$ need not be
  principal, so their gcd and lcm are naturally ideals rather than elements.
]

=== Coprime Factors and Remainders

#definition(title: "Coprime Ideals")[
  Two ideals $I$ and $J$ are #emph[coprime] if

  $ I+J=A $

  Equivalently, no nonzero prime ideal occurs in both prime factorizations.
]

#proposition(title: "Intersection, Product, and the Chinese Remainder Theorem")[
  If $I$ and $J$ are coprime, then

  $ I inter J=I J $

  More generally, if

  $ I=product_(i=1)^r frak(p)_i^(n_i) $

  with distinct prime ideals $frak(p)_i$, then

  $ I=inter.big_(i=1)^r frak(p)_i^(n_i) $

  and the natural residue map induces an isomorphism

  $ A slash I -> product_(i=1)^r A slash frak(p)_i^(n_i) $
]

#proof[
  Coprimality means that at every prime, at least one of the two exponents is
  zero. Their sum therefore equals their maximum, so the exponent dictionary
  gives $I J=I inter J$. Distinct nonzero prime ideals are maximal and hence
  pairwise coprime; the intersection formula follows by induction. The final
  isomorphism is the Chinese remainder theorem.
]

#corollary(title: "The Radical of an Ideal")[
  If

  $ I=product_(i=1)^r frak(p)_i^(n_i), quad n_i>=1 $

  then

  $ sqrt(I)=product_(i=1)^r frak(p)_i=inter.big_(i=1)^r frak(p)_i $

  Thus $I$ is radical if and only if every exponent in its prime factorization
  is $1$.
]

=== Examples

#example(title: "Ideals of the Integers")[
  The nonzero prime ideals of $ZZ$ are $(p)$ for rational primes $p$. If

  $ n=plus.minus product_p p^(e_p) $

  is the ordinary prime factorization of a nonzero integer, then

  $ (n)=product_p (p)^(e_p) $

  Thus unique factorization of ideals in $ZZ$ is exactly ordinary unique
  factorization, written in ideal language.
]

#example(title: [Prime-Ideal Factorization in $ZZ[sqrt(-5)]$])[
  In $A=ZZ[sqrt(-5)]$, put

  $ frak(p)_2=(2,1+sqrt(-5)) $

  $ frak(p)_3=(3,1+sqrt(-5)), quad frak(q)_3=(3,1-sqrt(-5)) $

  Direct multiplication gives

  $ (2)=frak(p)_2^2, quad (3)=frak(p)_3 frak(q)_3 $

  and

  $ (1+sqrt(-5))=frak(p)_2 frak(p)_3 $

  $ (1-sqrt(-5))=frak(p)_2 frak(q)_3 $

  Consequently, both element factorizations of $6$ induce the same unique
  factorization of its principal ideal:

  $ (6)=frak(p)_2^2 frak(p)_3 frak(q)_3 $

  The ambiguity among elements disappears after passing to ideals.
]

== Divisors and the Class Group

=== The Correspondence with Divisors

#definition(title: "Divisors")[
  The #emph[divisor group] of $A$, denoted $"Div"(A)$, is the free abelian group
  on the nonzero prime ideals of $A$. Its elements are finite formal sums

  $ D=sum_frak(p) n_(frak(p)) [frak(p)], quad n_(frak(p)) in ZZ $

  A divisor is #emph[effective] if every coefficient is nonnegative. For
  $x in K^times$, its #emph[principal divisor] is

  $ "div"(x)=sum_frak(p) v_(frak(p)) (x)[frak(p)] $

  where $v_(frak(p)) (x)$ is the normalized valuation of $x$ in the DVR
  $A_(frak(p))$.
]

Because $A$ is one-dimensional, its nonzero prime ideals are exactly the
codimension-one points of $"Spec" A$. Thus this is also the group of Weil
divisors on $"Spec" A$.

#theorem(title: "Fractional Ideals as Divisors")[
  Let $"FracId"(A)$ denote the group of nonzero fractional ideals. The map

  $ Phi(I)=sum_frak(p) v_(frak(p)) (I)[frak(p)] $

  is an isomorphism of abelian groups

  $ Phi: "FracId"(A) -> "Div"(A) $

  Under this correspondence:

  + ideal multiplication corresponds to addition of divisors;

  + integral ideals correspond to effective divisors;

  + the principal fractional ideal $(x)$ corresponds to the principal divisor
    $"div"(x)$.
]

#proof[
  Multiplicativity follows from
  $v_(frak(p)) (I J)=v_(frak(p)) (I)+v_(frak(p)) (J)$. The prime-ideal
  factorization above shows that $Phi$ is injective. Conversely, for a finite
  divisor $D=sum_frak(p) n_(frak(p))[frak(p)]$, the fractional ideal

  $ I_D=product_frak(p) frak(p)^(n_(frak(p))) $

  satisfies $Phi(I_D)=D$, proving surjectivity. The remaining claims follow
  from the exponent dictionary.
]

=== Two Viewpoints on the Class Group

#definition(title: "Ideal Class Group: The Ideal-Theoretic Viewpoint")[
  Let $"PrinId"(A)$ be the subgroup of $"FracId"(A)$ consisting of principal
  fractional ideals $(x)=x A$ with $x in K^times$. The #emph[ideal class group]
  of $A$ is

  $ "Cl"_id (A):="FracId"(A) slash "PrinId"(A) $

  Thus two fractional ideals $I$ and $J$ determine the same ideal class if and
  only if $I=x J$ for some $x in K^times$. We write the quotient law additively,
  so $[I J]=[I]+[J]$.
]

Multiplying by $x$ merely rescales an $A$-lattice inside the one-dimensional
$K$-vector space $K$. The quotient forgets this choice of scale and remembers
only the intrinsic isomorphism class of the ideal. Equivalently, the ideal
class group completes the exact sequence

$ 0 -> A^times -> K^times -> "FracId"(A) -> "Cl"_"id" (A) -> 0 $

where $x in K^times$ maps to $(x)$.

#definition(title: "Divisor Class Group: The Geometric Viewpoint")[
  Put $X="Spec" A$. The subgroup of #emph[principal divisors] is

  $ "Prin"(X)={"div"(x) | x in K^times} subset.eq "Div"(X) $

  Two divisors $D$ and $E$ are #emph[linearly equivalent] if

  $ D-E="div"(x) $

  for some $x in K^times$. The #emph[divisor class group] is

  $ "Cl"_"div" (X):="Div"(X) slash "Prin"(X) $

  Its elements are therefore linear-equivalence classes of divisors.
]

This second definition has a geometric interpretation. A nonzero prime ideal
$frak(p)$ is a closed codimension-one point of the one-dimensional scheme $X$.
A divisor

$ D=sum_frak(p) n_(frak(p))[frak(p)] $

is a finite collection of closed points with integer multiplicities. Positive
coefficients describe zeros, while negative coefficients describe poles. For a
rational function $x in K^times$, the coefficient of $[frak(p)]$ in
$"div"(x)$ is its order of vanishing at $frak(p)$. Passing to divisor classes
means that divisors differing only by the zeros and poles of a global rational
function are regarded as geometrically equivalent.

#proposition(title: "Effective Divisors and Their Ideal Sheaves")[
  Let

  $ D=sum_frak(p) n_(frak(p))[frak(p)] $

  be an effective divisor, and set

  $ I_D=product_frak(p) frak(p)^(n_(frak(p))) $

  Then $I_D$ is the integral ideal cutting out the corresponding
  zero-dimensional closed subscheme of $X$. At $frak(p)$ its multiplicity is

  $ "length"_(A_(frak(p))) (A_(frak(p)) slash I_D A_(frak(p)))=n_(frak(p)) $

  The associated ideal sheaf is

  $ tilde(I_D)=cal(O)_X (-D) $

  More generally, for an arbitrary divisor $D$, the same product defines a
  fractional ideal $I_D$, and the global sections of its associated line bundle
  are

  $ Gamma(X,cal(O)_X (D))={x in K | v_(frak(p)) (x)+n_(frak(p))>=0 " for every " frak(p)}=I_D^(-1) $
]

#proof[
  Localizing at $frak(p)$ gives
  $I_D A_(frak(p))=frak(p)^(n_(frak(p))) A_(frak(p))$. If $pi$ is a
  uniformizer of the DVR $A_(frak(p))$, then the quotient is
  $A_(frak(p)) slash (pi^(n_(frak(p))))$, which has length
  $n_(frak(p))$. The descriptions of $cal(O)_X (-D)$ and $cal(O)_X (D)$ follow
  from the same local valuation inequalities.
]

#theorem(title: "Comparison of the Two Viewpoints")[
  The fractional-ideal--divisor isomorphism $Phi$ sends principal fractional
  ideals to principal divisors and therefore induces an isomorphism

  $ Phi_"cl": "Cl"_"id" (A) -> "Cl"_"div" ("Spec" A) $

  Hence both groups are denoted simply by $"Cl"(A)$. Moreover, there is a
  canonical isomorphism between $"Cl"(A)$ and the Picard group of
  $X="Spec" A$, the group of isomorphism classes of line bundles on $X$.
]

#proof[
  We have already seen that $Phi((x))="div"(x)$. Since $Phi$ is an isomorphism
  before taking quotients, it remains an isomorphism after quotienting by the
  corresponding principal subgroups.

  Every fractional ideal is a projective $A$-module of rank one, so its
  associated sheaf is a line bundle on $X$. Conversely, every line bundle on an
  affine scheme arises from a projective module of rank one; after choosing a
  trivialization over the generic point, that module becomes a fractional ideal
  in $K$. Changing the trivialization multiplies the ideal by an element of
  $K^times$, so its ideal class is well-defined.
]

#remark(title: "The Sign Convention")[
  If $Phi(I)=D$, then

  $ tilde(I)=cal(O)_X (-D) $

  Thus the direct identification of ideal classes with divisor classes uses
  $I mapsto D$, while the line bundle naturally attached to $I$ is
  $cal(O)_X (-D)$. Equivalently, $cal(O)_X (D)$ corresponds to $I^(-1)$. This
  minus sign is the only convention one must watch when moving among ideals,
  divisors, and line bundles.
]

#remark(title: "What Does the Class Group Measure?")[
  The class group packages several related obstructions.

  + #emph[Failure of ideals to be principal.] The class $[I]$ is zero exactly
    when $I$ is principal. Hence

    $ "Cl"(A)=0 <=> A " is a PID" $

  + #emph[Failure of unique factorization of elements.] Ideals in a Dedekind
    domain always factor uniquely into prime ideals, but the prime ideals need
    not be generated by prime elements. The class group records precisely this
    obstruction. In fact,

    $ "Cl"(A)=0 <=> A " is a PID" <=> A " is a UFD" $

    Relations among the classes of prime ideals explain how distinct
    factorizations of elements can produce the same principal ideal.

  + #emph[Nontrivial line bundles.] The group $"Cl"(A)$ classifies rank-one
    projective $A$-modules, or equivalently line bundles on $"Spec" A$. The
    zero class is the trivial line bundle $cal(O)_X$.

  + #emph[Arithmetic complexity.] When $A$ is the ring of integers of a number
    field, $"Cl"(A)$ is finite. Its order is the #emph[class number]. It gives a
    numerical measure of how far the ring is from being principal.
]

#example(title: "The Integers")[
  Every nonzero fractional ideal of $ZZ$ is $q ZZ$ for some $q in QQ^times$.
  If $q=plus.minus product_p p^(n_p)$, then
  $Phi(q ZZ)=sum_p n_p [p]$. Every divisor is principal, so $"Cl"(ZZ)=0$.
]

#example(title: [The Class Group of $ZZ[sqrt(-5)]$])[
  Consider the Dedekind domain $A=ZZ[sqrt(-5)]$, the ring of integers of
  $QQ(sqrt(-5))$. The ideal

  $ frak(p)=(2,1+sqrt(-5)) $

  satisfies $frak(p)^2=(2)$, but $frak(p)$ is not principal: a generator would
  have norm $2$, whereas the equation $a^2+5b^2=2$ has no integer solutions.
  Therefore $[frak(p)]$ is a nonzero class with

  $ 2[frak(p)]=0 $

  We now show that there are no other ideal classes. For a nonzero integral
  ideal $J$, write $"N"(J)=|A slash J|$. The field $QQ(sqrt(-5))$ has
  discriminant $D_K=-20$. The Minkowski bound for an imaginary quadratic field
  says that every ideal class contains a nonzero integral ideal $J$ such that

  $ "N"(J)<=(2/pi) sqrt(|D_K|)=(2/pi) sqrt(20)<3 $

  Since $"N"(J)$ is a positive integer, it is either $1$ or $2$. If
  $"N"(J)=1$, then $J=A$ and its class is zero. If $"N"(J)=2$, then
  $A slash J$ is the field $FF_2$. The image of $sqrt(-5)$ in this field must
  satisfy $t^2+1=0$, whose only root is $t=1$. Hence the quotient map has
  kernel

  $ J=(2,1+sqrt(-5))=frak(p) $

  Thus every ideal class is either $[A]$ or $[frak(p)]$. These classes are
  distinct because $frak(p)$ is not principal, and $2[frak(p)]=0$. Therefore

  $ "Cl"(ZZ[sqrt(-5)])={ [A],[frak(p)] } $

  As a group, it is isomorphic to $ZZ slash 2 ZZ$, and the class number is $2$.

  The prime-ideal factorizations computed above show how this nonzero
  two-torsion class accounts for the two element factorizations
  $6=2 dot 3=(1+sqrt(-5))(1-sqrt(-5))$: uniqueness remains true for ideals,
  while the nonprincipal prime ideals obstruct uniqueness for elements.
]

=== Class Number and an Ideal-Theoretic Characterization

#definition(title: "Class Number")[
  The #emph[class number] of a Dedekind domain $A$ is the cardinality of its
  class group:

  $ h(A):=|"Cl"(A)| $

  For a general Dedekind domain this cardinality may be infinite. When it is
  finite, $h(A)$ is a positive integer. In particular,

  $ h(A)=1 <=> "Cl"(A)=0 <=> A " is a PID" <=> A " is a UFD" $

  If $A$ is the ring of integers of a number field, then $h(A)$ is always
  finite.
]

#theorem(title: "Dedekind Domains via Invertible Ideals")[
  Let $A$ be a domain that is not a field, with fraction field $K$. The
  following conditions are equivalent.

  + The ring $A$ is a Dedekind domain.

  + Every nonzero integral ideal $I subset.eq A$ is invertible as a fractional
    ideal; equivalently,

    $ I(A:I)=A $

    where $(A:I)={x in K | x I subset.eq A}$.

  + Every nonzero fractional ideal of $A$ is invertible.

  Thus invertibility of all nonzero ideals may be taken as another equivalent
  definition of a Dedekind domain.
]

#proof[
  If $A$ is Dedekind, every nonzero fractional ideal is invertible by the
  invertibility theorem above, so the first condition implies the third, and
  the third plainly implies the second.

  Now suppose that every nonzero integral ideal is invertible. Such an ideal
  is automatically finitely generated. Indeed, write

  $ 1=sum_(i=1)^n x_i y_i, quad x_i in I, y_i in (A:I) $

  For any $x in I$,

  $ x=sum_(i=1)^n (y_i x)x_i $

  and every coefficient $y_i x$ lies in $A$. Hence $I$ is generated by
  $x_1,dots,x_n$. Since every ideal of $A$ is finitely generated, $A$ is
  Noetherian.

  Let $frak(p)$ be a nonzero prime ideal and put $R=A_(frak(p))$. Every
  nonzero ideal of $R$ has the form $I R$ for a nonzero ideal $I$ of $A$.
  Localization preserves invertibility, so $I R$ is an invertible ideal of the
  local ring $R$. Every invertible ideal of a local ring is principal: if

  $ 1=sum_(i=1)^n u_i v_i, quad u_i in I R, v_i in (I R)^(-1) $

  then some product $u_i v_i$ is a unit, and the corresponding $u_i$ generates
  $I R$. Thus every nonzero ideal of $R$ is principal. Since $R$ is local and
  not a field, it is a DVR. Therefore $A_(frak(p))$ is a DVR for every
  nonzero prime $frak(p)$, and the local characterization proved earlier shows
  that $A$ is Dedekind.
]
