#import "../template.typ": *
#import "@preview/fletcher:0.5.8": *
#import "@preview/cetz:0.5.2"

#show: doc => conf(
  easy: true,
  doc,
)

= Two Important Theorems

The ideal class group was introduced algebraically in Chapter 1. We now prove
that it is finite for the ring of integers of every number field. The bridge
from algebra to finiteness is geometric: embed fractional ideals as lattices in
a finite-dimensional real vector space, then force a lattice point to lie in a
sufficiently large convex body.

#quote[
  Geometry of numbers converts an infinite arithmetic problem into a bounded
  search inside Euclidean space.
]

== Lattices in Real Vector Spaces

Let $V$ be a real vector space of dimension $n$. After choosing a basis we may
identify $V$ with $RR^n$, but the definitions below do not depend on that
choice. As an additive group, $V$ is an LCA group and therefore carries Haar
measure, unique up to a positive scalar.

=== Discrete and Cocompact Subgroups

#definition(title: "Discrete and Cocompact Subgroups")[
  Let $G$ be a Hausdorff topological group and let $H subset.eq G$ be a
  subgroup.

  + The subgroup $H$ is #emph[discrete] if its subspace topology is discrete.
    Equivalently, the identity has a neighborhood $U$ such that
    $U inter H={0}$.
  + The subgroup $H$ is #emph[cocompact] if the quotient space $G slash H$ is
    compact.
]

#proposition(title: "Structure of Discrete Subgroups of a Real Vector Space")[
  Let $Gamma subset.eq V$ be a discrete subgroup, and put

  $ W="span"_RR (Gamma) $

  If $dim_RR W=m$, then $Gamma$ is a free abelian group of rank $m$. More
  precisely, there is an $RR$-basis $gamma_1,dots,gamma_m$ of $W$ contained
  in $Gamma$ such that

  $ Gamma=ZZ gamma_1+dots+ZZ gamma_m $

  In particular, $Gamma$ is a full lattice in its real span.
]

#proof[
  Choose $RR$-linearly independent elements $e_1,dots,e_m in Gamma$ forming a
  basis of $W$, and let

  $ Lambda:=ZZ e_1+dots+ZZ e_m $

  The half-open parallelepiped

  $ F:={sum_(i=1)^m t_i e_i | 0<=t_i<1} $

  contains a representative of every coset of $Lambda$ in $W$ and has compact
  closure.

  A discrete subgroup of the finite-dimensional metric group $W$ is closed.
  Indeed, if a sequence in $Gamma$ converges, then the differences of two
  sufficiently late terms lie in an isolating neighborhood of $0$, so the
  sequence is eventually constant. Consequently, a compact set meets
  $Gamma$ in only finitely many points. It follows that

  $ Gamma inter overline(F) $

  is finite. Reducing every element of $Gamma$ modulo $Lambda$ into
  $overline(F)$ shows that $Gamma slash Lambda$ is finite. Hence $Gamma$ is
  finitely generated.

  Since $Gamma$ is a finitely generated subgroup of the torsion-free group
  $V$, it is free abelian. Its rank is $m$: it contains the rank-$m$ group
  $Lambda$, and the quotient $Gamma slash Lambda$ is finite. Choosing a
  $ZZ$-basis $gamma_1,dots,gamma_m$ of $Gamma$ gives an $RR$-basis of $W$.
]

#remark(title: "Finite Generation Alone Does Not Imply Discreteness")[
  The subgroup

  $ ZZ+sqrt(2) ZZ subset.eq RR $

  is generated by two elements but is not discrete; in fact it is dense in
  $RR$. The missing condition is real linear independence. A subgroup of $V$
  generated by $RR$-linearly independent vectors is discrete, while an
  arbitrary finitely generated subgroup need not be.
]

#definition(title: "Real Lattice")[
  A #emph[full lattice] in $V$ is a subgroup of the form

  $ Lambda=ZZ e_1+dots+ZZ e_n $

  for an $RR$-basis $e_1,dots,e_n$ of $V$. In this chapter, #emph[lattice]
  always means full lattice.
]

#proposition(title: "Topological Characterization of a Full Lattice")[
  A subgroup $Lambda subset.eq V$ is a full lattice if and only if it is
  discrete and cocompact.
]

#proof[
  A subgroup generated by an $RR$-basis becomes $ZZ^n subset.eq RR^n$ after a
  linear change of coordinates. It is discrete, and its quotient is the
  compact torus

  $ RR^n slash ZZ^n tilde.eq (RR slash ZZ)^n $

  Conversely, let $Gamma subset.eq V$ be discrete and cocompact. The preceding
  proposition says that it is a lattice in
  $W="span"_RR (Gamma)$. If $W!=V$, the quotient $V slash Gamma$ maps
  continuously onto the noncompact vector space $V slash W$, contradicting
  compactness. Thus $W=V$.
]

#example(title: "Linear Images of the Standard Lattice")[
  Every lattice in $RR^n$ has the form

  $ Lambda=A ZZ^n $

  for some $A in "GL"_n (RR)$. Two matrices $A$ and $B$ determine the same
  lattice exactly when $A^(-1)B in "GL"_n (ZZ)$. Thus a lattice is a choice of
  integral coordinates inside a real vector space, with integral
  change-of-basis matrices regarded as invisible.
]

=== Fundamental Domains and Covolume

#definition(title: "Fundamental Parallelepiped and Fundamental Domain")[
  Let $Lambda=sum_(i=1)^n ZZ e_i$ be a lattice in $V$. Its
  #emph[fundamental parallelepiped] is

  $ cal(P)(e_1,dots,e_n)
    :={sum_(i=1)^n t_i e_i | 0<=t_i<1} $

  More generally, a measurable subset $F subset.eq V$ is a
  #emph[fundamental domain] for $Lambda$ if every coset of $Lambda$ in $V$
  contains exactly one point of $F$. Equivalently, the translates
  ${F+lambda:lambda in Lambda}$ form a disjoint partition of $V$.
]

#remark(title: "Why the Parallelepiped Is Half-Open")[
  A closed parallelepiped contains several representatives of boundary
  cosets, while an open one misses them. The half-open convention chooses one
  representative on each boundary face. Boundaries have measure zero, so this
  convention changes neither volume nor integration, but it makes the quotient
  statement literally true.
]

#proposition(title: "All Fundamental Domains Have the Same Measure")[
  Fix Haar measure $mu$ on $V$. If $F$ and $F'$ are measurable fundamental
  domains for a lattice $Lambda$, then

  $ mu(F)=mu(F') $

  This common value is finite and positive.
]

#proof[
  Since $Lambda tilde.eq ZZ^n$ is countable and the translates of $F'$ partition
  $V$, countable additivity and translation invariance give

  $ mu(F)
    =sum_(lambda in Lambda) mu(F inter (F'+lambda))
    =sum_(lambda in Lambda) mu((F-lambda) inter F') $

  Reindexing $lambda mapsto -lambda$ and using the fact that the translates of
  $F$ also partition $V$, the last sum equals $mu(F')$. A fundamental
  parallelepiped has compact closure, so its measure is finite. It contains a
  nonempty open subset, whose Haar measure is positive. Every fundamental
  domain has the same measure and hence is also finite and nonzero.
]

#definition(title: "Covolume")[
  The #emph[covolume] of a lattice $Lambda subset.eq V$ is

  $ "covol"_mu (Lambda):=mu(F) $

  where $F$ is any fundamental domain. It depends on the normalization of
  $mu$, but the ratio of two covolumes does not.
]

#proposition(title: "Determinant Formula for Covolume")[
  Let $e_1,dots,e_n$ be a basis of a lattice $Lambda$. After identifying
  $V$ with $RR^n$ and taking ordinary Lebesgue measure, let $A$ be the matrix
  whose columns are the $e_i$. Then

  $ "covol"(Lambda)=abs(det A) $

  More invariantly, if $V$ has an inner product and Haar measure is its
  associated Euclidean volume, then

  $ "covol"(Lambda)=sqrt(det G), quad G_(i j):=e_i dot e_j $
]

#proof[
  The linear map $A$ sends the standard half-open cube to
  $cal(P)(e_1,dots,e_n)$. The automorphism-modulus formula from Chapter 11
  gives

  $ mu(A S)=abs(det A) mu(S) $

  The standard cube has volume $1$, proving the first formula. For the second,
  the Gram matrix is $A^T A$, so

  $ sqrt(det(A^T A))=sqrt(det(A)^2)=abs(det A) $
]

#proposition(title: "Index and Covolume")[
  If $Lambda' subset.eq Lambda$ are lattices in $V$, then the index is finite
  and

  $ "covol"(Lambda')=[Lambda:Lambda'] "covol"(Lambda) $
]

#proof[
  Choose a $ZZ$-basis of $Lambda$ and a $ZZ$-basis of $Lambda'$. The inclusion
  $Lambda'->Lambda$ is represented by an integer matrix $A$ with
  $det A!=0$. The adjugate identity shows that

  $ abs(det A) Lambda subset.eq Lambda' $

  so $Lambda slash Lambda'$ is a quotient of the finite group
  $Lambda slash abs(det A)Lambda$. In particular, the index is finite.

  Let $F$ be a fundamental domain for $Lambda$, and choose a finite set $R$ of
  representatives for $Lambda slash Lambda'$. Then

  $ F':=union_(rho in R) (F+rho) $

  is a fundamental domain for $Lambda'$, and the union is disjoint. Therefore

  $ mu(F')=sum_(rho in R) mu(F+rho)=abs(R) mu(F) $

  which is the claimed formula.
]

#remark(title: "Algebraic Index Becomes Geometric Volume")[
  A smaller sublattice has a larger fundamental domain. The finite group
  $Lambda slash Lambda'$ counts exactly how many fundamental cells of
  $Lambda$ are needed to make one cell of $Lambda'$. This is the real-linear
  counterpart of the module-index and divisor viewpoints developed in
  Chapter 4.
]

#theorem(title: "Blichfeldt's Lemma")[
  Let $Lambda subset.eq V$ be a lattice and let $S subset.eq V$ be measurable.
  If

  $ mu(S)>"covol"(Lambda) $

  then there exist distinct points $x,y in S$ such that

  $ x-y in Lambda $
]

#proof[
  Let $F$ be a fundamental domain and define the integer-valued counting
  function

  $ n_S (u):=sum_(lambda in Lambda) 1_S (u+lambda) quad (u in F) $

  Tonelli's theorem and the partition
  $V=union_(lambda in Lambda)(F+lambda)$ give

  $ integral_F n_S (u) dif mu(u)
    =sum_(lambda in Lambda) integral_F 1_S (u+lambda) dif mu(u)
    =mu(S) $

  If $n_S (u)<=1$ everywhere, the left-hand side would be at most
  $mu(F)="covol"(Lambda)$, contrary to the hypothesis. Hence some $u in F$
  admits distinct $lambda_1,lambda_2 in Lambda$ with
  $u+lambda_1,u+lambda_2 in S$. Their difference is the nonzero lattice vector
  $lambda_1-lambda_2$.
]

== Minkowski Lattices

The previous section compared the volume of a set with the volume of one
lattice cell. Minkowski's insight is that symmetry and convexity turn two
congruent points into a nonzero lattice point inside the original set.

=== Minkowski's Lattice Point Theorem

#definition(title: "Symmetric Convex Body")[
  A subset $S$ of a real vector space is #emph[symmetric] if $S=-S$, and it is
  #emph[convex] if

  $ t x+(1-t)y in S $

  for all $x,y in S$ and $0<=t<=1$. A #emph[convex body] is a compact convex
  set with nonempty interior.
]

#theorem(title: "Minkowski's Lattice Point Theorem")[
  Let $Lambda$ be a lattice in an $n$-dimensional real vector space $V$. If
  $S subset.eq V$ is symmetric, convex, and measurable, and

  $ mu(S)>2^n "covol"(Lambda) $

  then $S$ contains a nonzero point of $Lambda$.
]

#proof[
  The dilated set $(1/2)S$ has measure

  $ mu((1/2)S)=2^(-n)mu(S)>"covol"(Lambda) $

  Blichfeldt's lemma gives distinct $x,y in (1/2)S$ with
  $x-y in Lambda$. Write $x=s_1/2$ and $y=s_2/2$ with $s_1,s_2 in S$.
  Symmetry gives $-s_2 in S$, and convexity gives

  $ x-y=(s_1+(-s_2))/2 in S $

  Since $x!=y$, this is a nonzero point of $Lambda inter S$.
]

#remark(title: "The Meaning of the Factor $2^n$")[
  The proof must first shrink $S$ by $1/2$ so that the difference of two
  points returns to $S$. Volume scales once in each of the $n$ real
  directions, producing $2^n$. This factor is geometric rather than
  arithmetic.
]

#corollary(title: "Closed-Boundary Version")[
  If $S$ is a symmetric convex body with

  $ mu(S)>=2^n "covol"(Lambda) $

  then $S$ contains a nonzero lattice point.
]

#proof[
  For every $epsilon>0$, the slightly enlarged body
  $(1+epsilon)S$ satisfies the strict inequality and contains a nonzero point
  of $Lambda$. Fixing one enlargement, its intersection with the discrete set
  $Lambda$ is finite. Along a sequence $epsilon->0$, one lattice point occurs
  infinitely often and therefore belongs to the closed set $S$.
]

=== The Minkowski Space of a Number Field

Let $K$ be a number field of degree $n$ and signature $(r,s)$, so
$n=r+2s$. Choose its real embeddings

$ sigma_1,dots,sigma_r:K->RR $

and one embedding $tau_j:K->CC$ from each of the $s$ conjugate pairs.

#definition(title: "Minkowski Space and Minkowski Embedding")[
  The #emph[Minkowski space] of $K$ is

  $ K_RR:=K ⊗_QQ RR tilde.eq RR^r times CC^s $

  regarded as a real vector space of dimension $n$. The
  #emph[Minkowski embedding] is

  $ iota_K:K->K_RR, quad
    x mapsto (sigma_1(x),dots,sigma_r (x),tau_1(x),dots,tau_s (x)) $

  We usually identify $K$ with its image under $iota_K$.
]

#remark(title: "Why Only One Embedding from Each Complex Pair Appears")[
  A complex coordinate already has two real dimensions. Listing both
  $tau_j (x)$ and $overline(tau_j (x))$ would be useful algebraically but would
  double-count the real vector-space dimension. The space
  $RR^r times CC^s$ keeps one complex coordinate while remembering its two real
  directions.
]

#definition(title: "Canonical Inner Product and Haar Measure")[
  #linebreak()
  For $z=(x_1,dots,x_r,z_1,dots,z_s)$ and
  $w=(y_1,dots,y_r,w_1,dots,w_s)$ in $K_RR$, define

  $ (z,w)_K
    :=sum_(i=1)^r x_i y_i
      +2 sum_(j=1)^s "Re"(z_j overline(w_j)) $

  If $mu_0$ is ordinary Lebesgue measure in the real coordinates
  $x_i,"Re"(z_j),"Im"(z_j)$, define the #emph[canonical Minkowski measure] by

  $ mu_K:=2^s mu_0 $

  This is precisely the Euclidean volume measure associated with the canonical
  inner product.
]

#remark(title: [The Factor $2^s$])[
  Each complex coordinate contributes the quadratic form

  $ 2(u^2+v^2) $

  on its two real coordinates. Its Gram determinant is $4$, so the associated
  area form is twice ordinary area. One factor of $2$ occurs for each of the
  $s$ complex places. This normalization makes the discriminant appear without
  an extra factor of $2^(-s)$.
]

#theorem(title: "Fractional Ideals as Minkowski Lattices")[
  The image of $cal(O)_K$ in $K_RR$ is a lattice. More generally, every
  nonzero fractional ideal $I$ of $cal(O)_K$ is a lattice in $K_RR$.
]

#proof[
  The ring $cal(O)_K$ is a free $ZZ$-module of rank $n$. If
  $omega_1,dots,omega_n$ is an integral basis, it is also a $QQ$-basis of $K$.
  After base change from $QQ$ to $RR$, the vectors
  $iota_K(omega_1),dots,iota_K(omega_n)$ form an $RR$-basis of $K_RR$. Hence

  $ iota_K (cal(O)_K)=sum_(i=1)^n ZZ iota_K (omega_i) $

  is a lattice.

  A nonzero fractional ideal $I$ is a free $ZZ$-module of rank $n$: after
  clearing denominators it becomes a nonzero integral ideal of finite index in
  $cal(O)_K$. Any $ZZ$-basis of $I$ is therefore an $RR$-basis of $K_RR$, so
  its image is also a lattice.
]

#quote[
  An ideal is discrete algebra in $K$; the Minkowski embedding turns it into a
  periodic geometric grid in $K_RR$.
]

=== Discriminants and Covolumes

#theorem(title: "Covolume of the Ring of Integers")[
  With respect to the canonical Minkowski measure,

  $ "covol"(cal(O)_K)=sqrt(abs(d_K)) $

  where $d_K$ is the absolute discriminant of $K$.
]

#proof[
  Choose an integral basis $omega_1,dots,omega_n$ and list all $n$ complex
  embeddings of $K$ as $rho_1,dots,rho_n$, including both members of every
  complex-conjugate pair. Let

  $ A=(rho_i (omega_j))_(i,j) $

  be the embedding matrix. Chapter 10 gives

  $ d_K=det(A)^2 $

  The Gram matrix $G$ of the vectors $iota_K (omega_j)$ for the canonical inner
  product has entries

  $ G_(i,j)=sum_(rho:K->CC) rho(omega_i) overline(rho(omega_j)) $

  and therefore $G=A^T overline(A)$. Consequently,

  $ det G=overline(det A) det A=abs(det A)^2=abs(d_K) $

  The Gram determinant formula for covolume now yields

  $ "covol"(cal(O)_K)=sqrt(det G)=sqrt(abs(d_K)) $
]

#definition(title: "Absolute Norm of a Fractional Ideal")[
  Recall the relative ideal norm from Chapter 4. For a nonzero fractional
  ideal $I$ of $cal(O)_K$, the fractional ideal
  $"N"_(cal(O)_K slash ZZ) (I)$ is principal. Its unique positive rational
  generator is the #emph[absolute norm] $"N"(I)$:

  $ "N"_(cal(O)_K slash ZZ) (I)="N"(I) ZZ $

  When $I subset.eq cal(O)_K$ is integral,

  $ "N"(I)=abs(cal(O)_K slash I) $
]

#corollary(title: "Covolume of a Fractional Ideal")[
  For every nonzero fractional ideal $I$,

  $ "covol"(I)="N"(I) sqrt(abs(d_K)) $
]

#proof[
  For an integral ideal $I$, the index--covolume formula gives

  $ "covol"(I)=[cal(O)_K:I] "covol"(cal(O)_K)
    ="N"(I) sqrt(abs(d_K)) $

  For a fractional ideal, choose $0!=b in ZZ$ with $b I subset.eq cal(O)_K$.
  Multiplication by $b$ scales both covolume and ideal norm by $b^n$, so the
  same identity follows after cancelling $b^n$.
]

#example(title: "The Gaussian Lattice")[
  For $K=QQ(i)$, the Minkowski space is $CC$, the ring of integers is
  $ZZ[i]$, and $d_K=-4$. The ordinary Euclidean fundamental square has area
  $1$, but the canonical Minkowski measure is twice ordinary area because
  $s=1$. Therefore

  $ "covol"(ZZ[i])=2=sqrt(abs(-4)) $

  This example makes the normalization $mu_K=2^s mu_0$ visible.
]

=== The Minkowski Bound

#lemma(title: "Volume of the Minkowski Body")[
  For $t>0$, define

  $ S_t:={z=(x_1,dots,x_r,z_1,dots,z_s) in RR^r times CC^s |
    sum_(i=1)^r abs(x_i)+2 sum_(j=1)^s abs(z_j)<=t} $

  Then $S_t$ is a symmetric convex body and

  $ mu_K(S_t)=(2^r pi^s slash n!) t^n $
]

#proof[
  Symmetry is immediate. Convexity follows from the triangle inequality, and
  the defining inequality makes the set closed and bounded.

  To compute its volume, first choose the signs of the $r$ real coordinates,
  giving a factor $2^r$. For each complex coordinate write
  $z_j=r_j exp(i theta_j)$. The canonical measure contributes

  $ 2 r_j dif r_j dif theta_j $

  Put $v_j=2r_j$ and integrate $theta_j$ over $[0,2pi)$. Each complex
  coordinate then contributes the factor $pi v_j dif v_j$. We are left with

  $ 2^r pi^s integral_(u_i,v_j>=0, sum_i u_i+sum_j v_j<=t)
      product_(j=1)^s v_j dif u dif v $

  The simplex integral is $t^(r+2s) slash (r+2s)! =t^n slash n!$.
  This gives the claimed formula.
]

#remark(title: "Why This Particular Body Is Chosen")[
  A Euclidean ball would also force lattice points, but the body $S_t$ is
  adapted to the field norm. Its defining sum is an arithmetic mean of the
  $n$ archimedean sizes, while the field norm is their geometric mean. The
  AM--GM inequality therefore converts membership in $S_t$ directly into a
  bound on $abs("N"_(K slash QQ)(a))$.
]

#definition(title: "Minkowski Constant")[
  For a number field $K$ of degree $n$ with $s$ complex places, define

  $ m_K:=n! slash n^n (4 slash pi)^s sqrt(abs(d_K)) $
]

#theorem(title: "Minkowski Bound for Fractional Ideals")[
  Let $I$ be a nonzero fractional ideal of $cal(O)_K$. There exists
  $0!=a in I$ such that

  $ abs("N"_(K slash QQ) (a))<=m_K "N"(I) $
]

#proof[
  Choose $t>0$ such that

  $ (t slash n)^n>m_K "N"(I) $

  Since $n=r+2s$, the volume formula and the covolume formula give

  $ mu_K (S_t)
    =(2^r pi^s slash n!)t^n
    >2^n "N"(I)sqrt(abs(d_K))
    =2^n "covol"(I) $

  Minkowski's lattice point theorem supplies a nonzero $a in I inter S_t$.
  Count the absolute value of each real embedding once and that of each
  complex embedding twice. The arithmetic--geometric mean inequality gives

  $ abs("N"_(K slash QQ) (a))
    =product_(i=1)^r abs(sigma_i (a))
      product_(j=1)^s abs(tau_j (a))^2
    <=lr((sum_i abs(sigma_i (a))+2 sum_j abs(tau_j (a))) slash n)^n
    <=(t slash n)^n $

  To replace the strict bound by a weak one, take a decreasing sequence of
  such $t$ approaching the threshold. The intersection of the lattice $I$
  with the first compact body is finite, so one nonzero lattice point occurs
  infinitely often and lies in the limiting closed body. It satisfies the
  claimed inequality.
]

#remark(title: "What the Bound Really Says")[
  The lattice $I$ may be infinite, but its cell volume is controlled exactly
  by $"N"(I)sqrt(abs(d_K))$. Minkowski's theorem forces a nonzero element of
  $I$ whose field norm is no larger than a universal multiple of this volume.
  The discriminant measures geometric sparsity; the factor
  $n! slash n^n (4 slash pi)^s$ records the chosen convex body.
]

== Finiteness of the Class Group

We now complete the argument promised in Chapter 1. It consists of two finite
reductions:

+ every ideal class contains an integral ideal of bounded norm;
+ only finitely many integral ideals have bounded norm.

=== A Small Integral Ideal in Every Class

#theorem(title: "Minkowski Representative Theorem")[
  Every class in $"Cl"(cal(O)_K)$ contains a nonzero integral ideal $I$ such
  that

  $ "N"(I)<=m_K $
]

#proof[
  Let $[J] in "Cl"(cal(O)_K)$ be represented by a nonzero fractional ideal
  $J$. Apply the Minkowski bound to $J^(-1)$. There is a nonzero
  $a in J^(-1)$ satisfying

  $ abs("N"_(K slash QQ) (a))
    <=m_K "N"(J^(-1))=m_K "N"(J)^(-1) $

  Put $I:=a J$. Since $a in J^(-1)$,

  $ I=a J subset.eq J^(-1) J=cal(O)_K $

  so $I$ is integral. Multiplication by the principal ideal $(a)$ does not
  change an ideal class, hence $[I]=[J]$. Finally, multiplicativity of the norm
  gives

  $ "N"(I)=abs("N"_(K slash QQ) (a)) "N"(J)<=m_K $
]

#remark(title: "Why We Apply Minkowski to the Inverse Ideal")[
  Applying the bound directly to $J$ produces a small element of $J$, but not
  necessarily an integral representative of the class $[J]$. Choosing
  $a in J^(-1)$ forces $a J subset.eq cal(O)_K$ while leaving the class
  unchanged. This is the decisive algebraic maneuver in the finiteness proof.
]

=== Finitely Many Ideals of Bounded Norm

#lemma(title: "Finiteness at Fixed Norm")[
  For each positive integer $m$, there are only finitely many integral ideals
  $I subset.eq cal(O)_K$ with $"N"(I)=m$.
]

#proof[
  If $"N"(I)=m$, then the finite abelian group
  $cal(O)_K slash I$ has order $m$. Multiplication by $m$ kills every element
  of this quotient, so

  $ m cal(O)_K subset.eq I subset.eq cal(O)_K $

  Thus $I slash m cal(O)_K$ is an ideal of the finite ring
  $cal(O)_K slash m cal(O)_K$. A finite ring has only finitely many subsets and
  hence only finitely many ideals. Therefore only finitely many such $I$ can
  occur.
]

#corollary(title: "Finitely Many Ideals of Bounded Norm")[
  For every real number $B>0$, the set

  $ {I subset.eq cal(O)_K | I!=0, "N"(I)<=B} $

  is finite.
]

#proof[
  The norm of a nonzero integral ideal is a positive integer. The displayed
  set is the finite union, over $1<=m<=floor(B)$, of the finite sets in the
  preceding lemma.
]

=== The Class Number Theorem

#theorem(title: "Finiteness of the Ideal Class Group")[
  For every number field $K$, the ideal class group

  $ "Cl"(cal(O)_K) $

  is finite. Equivalently, the class number

  $ h_K:=abs("Cl"(cal(O)_K)) $

  is a positive integer.
]

#proof[
  By the Minkowski representative theorem, every ideal class contains an
  integral ideal $I$ with $"N"(I)<=m_K$. By the bounded-norm finiteness
  corollary, there are only finitely many such ideals. The map from this finite
  set of ideals to $"Cl"(cal(O)_K)$ is surjective, so the class group is
  finite.
]

#quote[
  The proof is finite because geometry supplies a bounded representative for
  every class, and algebra says that a bounded norm permits only finitely many
  ideals.
]

#corollary(title: "A Finite Search for the Class Group")[
  The class group $"Cl"(cal(O)_K)$ is generated by the classes of prime ideals
  $frak(p)$ satisfying

  $ "N"(frak(p))<=m_K $
]

#proof[
  Every class has an integral representative $I$ of norm at most $m_K$.
  Factor it uniquely as

  $ I=product_(i=1)^ell frak(p)_i^(e_i) $

  Each factor satisfies
  $"N"(frak(p)_i)<="N"(I)<=m_K$, and
  $[I]=sum_i e_i [frak(p)_i]$ in the additive notation for the class group.
]

#example(title: "The Gaussian Integers Have Class Number One")[
  For $K=QQ(i)$, one has $n=2$, $s=1$, and $d_K=-4$. Hence

  $ m_K=(2! slash 2^2)(4 slash pi)sqrt(4)=4 slash pi<2 $

  Every ideal class contains an integral ideal of positive integer norm less
  than $2$, hence of norm $1$. Such an ideal is $cal(O)_K$ itself, so

  $ "Cl"(ZZ[i])=0 $
]

#example(title: [Recovering $"Cl"(ZZ[sqrt(-5)])$])[
  Let $K=QQ(sqrt(-5))$. Then $n=2$, $s=1$, and $d_K=-20$, so

  $ m_K=(2 slash pi)sqrt(20)<3 $

  Every class is represented by an ideal of norm $1$ or $2$. Norm $1$ gives
  the trivial class. There is exactly one ideal of norm $2$,

  $ frak(p)=(2,1+sqrt(-5)) $

  and Chapter 1 proved that $frak(p)$ is nonprincipal and
  $frak(p)^2=(2)$. Therefore

  $ "Cl"(ZZ[sqrt(-5)]) tilde.eq ZZ slash 2 ZZ $

  The abstract finiteness proof has become an explicit computation.
]

#remark(title: "Scope of the Argument")[
  The geometric proof above is tailored to number fields because
  $cal(O)_K$ is discrete inside the product of its archimedean completions.
  Global function fields also have finite class groups, but their geometry is
  organized by divisors on a projective curve, or equivalently by lattices at
  a chosen nonarchimedean place. The conclusion is the same, while the ambient
  geometry is different.
]

== Arakelov Divisors of a Global Field

For a function field, every place is a closed point of a proper curve and the
ordinary divisor group already sees all local directions. For a number field,
$"Spec" cal(O)_K$ sees only finite places. Arakelov divisors repair this
asymmetry by adjoining real coefficients at the archimedean places.

=== The Divisor Group and Its Degree

Let $K$ be a global field. For every nonarchimedean place $v$, write

$ q_v:=abs(kappa(v)) $

for the cardinality of its residue field, and let $v(x)$ be the normalized
discrete valuation, so that

$ norm(x)_v=q_v^(-v(x)) $

#definition(title: "Arakelov Divisor Group")[
  An #emph[additive Arakelov divisor] on $K$ is a formal sum

  $ D=sum_(v in M_K^0) n_v [v]+sum_(v in M_K^infinity) a_v [v] $

  where $n_v in ZZ$, $a_v in RR$, and only finitely many $n_v$ are nonzero.
  The group of Arakelov divisors is denoted by

  $ "Div"_"Ar" (K) $

  with addition defined coefficientwise. The second sum is absent for a
  global function field, since all of its places are nonarchimedean.
]

#remark(title: "Why the Coefficients Change at Infinity")[
  At a finite place the value group is discrete, so zeros and poles have
  integral orders. At a real or complex place, the map

  $ -log norm(dot)_v:K_v^times->RR $

  has a continuous real value group. The coefficients of an Arakelov divisor
  therefore reflect the topology of the corresponding local field: integers
  at discrete places and real numbers at continuous places.
]

#definition(title: "Degree and Effectivity")[
  The #emph[degree] of

  $ D=sum_(v in M_K^0) n_v [v]+sum_(v in M_K^infinity) a_v [v] $

  is

  $ deg_"Ar" (D)
    :=sum_(v in M_K^0) n_v log q_v
      +sum_(v in M_K^infinity) a_v $

  We call $D$ #emph[effective], and write $D>=0$, if every $n_v>=0$ and every
  $a_v>=0$.
]

#remark(title: "Function-Field Normalization")[
  If $K$ has full constant field $FF_q$, then
  $q_v=q^(deg(v))$. Hence

  $ deg_"Ar" (D)=log(q) sum_v n_v deg(v) $

  Dividing by $log(q)$ recovers the usual integer-valued degree of a divisor
  on the corresponding smooth projective curve.
]

#remark(title: "Additive and Multiplicative Conventions")[
  The multiplicative convention assigns to $D$ a family
  $c(D)=(c_v)_(v in M_K)$ by

  $ c_v=cases(q_v^(n_v) & v in M_K^0,
              exp(a_v) & v in M_K^infinity) $

  Addition of divisors becomes pointwise multiplication of the $c_v$, and

  $ product_v c_v=exp(deg_"Ar" (D)) $

  Thus the multiplicative #emph[size] of a divisor is simply the exponential
  of its additive degree.

  This is the Riemann--Roch sign convention: $c_v$ is the local bound in the
  inequality $norm(x)_v<=c_v$. Under this dictionary,

  $ c("div"_"Ar"(x))=(norm(x)_v^(-1))_v $

  Lecture 15 instead embeds $x$ as $(norm(x)_v)_v$. This replaces every
  divisor by its inverse, and therefore gives a canonically isomorphic divisor
  group and Picard group. The two conventions contain exactly the same
  information; only the direction of inequalities determines which sign is
  more convenient.
]

=== Principal Divisors and Arakelov Class Groups

#definition(title: "Arakelov Principal Divisor")[
  For $x in K^times$, define

  $ "div"_"Ar" (x)
    :=sum_(v in M_K^0) v(x)[v]
      -sum_(v in M_K^infinity) log norm(x)_v [v] $

  The subgroup of principal Arakelov divisors is

  $ "Princ"_"Ar" (K):={"div"_"Ar" (x) | x in K^times} $
]

#proposition(title: "The Product Formula as Degree Zero")[
  The principal-divisor map is a homomorphism

  $ "div"_"Ar":K^times->"Div"_"Ar"(K) $

  and every principal Arakelov divisor has degree zero:

  $ deg_"Ar" ("div"_"Ar" (x))=0 $
]

#proof[
  Additivity follows from $v(x y)=v(x)+v(y)$ and
  $log norm(x y)_v=log norm(x)_v+log norm(y)_v$. At finite places,

  $ v(x)log q_v=-log norm(x)_v $

  Thus

  $ deg_"Ar" ("div"_"Ar" (x))
    =-sum_(v in M_K) log norm(x)_v=0 $

  by the product formula.
]

#definition(title: "Arakelov Picard Groups")[
  The #emph[Arakelov Picard group] and its degree-zero subgroup are

  $ "Pic"_"Ar" (K)
    :="Div"_"Ar" (K) slash "Princ"_"Ar" (K) $

  $ "Pic"_"Ar"^0(K)
    :="Div"_"Ar"^0(K) slash "Princ"_"Ar" (K) $

  where

  $ "Div"_"Ar"^0(K):=ker(deg_"Ar") $

  These quotients are well-defined because principal divisors have degree
  zero.
]

#remark(title: "Topology on the Arakelov Class Group")[
  Give the free abelian group on $M_K^0$ the discrete topology and identify
  the archimedean factor with $RR^(abs(M_K^infinity))$, equipped with its
  Euclidean topology. We equip $"Div"_"Ar"(K)$ with the product topology and
  the two Picard groups with their quotient topologies. Thus the finite-place
  directions are discrete, while the infinite-place directions vary
  continuously.
]

#remark(title: "Relation with Ordinary Ideal Classes")[
  For a number field, projection onto the finite part defines

  $ "Div"_"Ar"(K)->"FracId"(cal(O)_K), quad
    sum_frak(p) n_frak(p)[frak(p)]+sum_(v|infinity) a_v [v]
      mapsto product_frak(p) frak(p)^(n_frak(p)) $

  It sends principal Arakelov divisors to principal fractional ideals and
  therefore induces a surjection

  $ "Pic"_"Ar" (K)->"Cl"(cal(O)_K) $

  The ordinary class group forgets every archimedean coefficient; the
  Arakelov Picard group remembers both the ideal class and its metric data at
  infinity.
]

=== Arakelov Riemann--Roch Sets

#definition(title: [The Set $L(D)$])[
  For $D in "Div"_"Ar" (K)$, define

  $ L(D):={0} union {x in K^times | "div"_"Ar" (x)+D>=0} $

  If

  $ D=sum_(v in M_K^0) n_v [v]+sum_(v in M_K^infinity) a_v [v] $

  then the conditions are

  $ v(x)>=-n_v quad (v in M_K^0) $

  $ norm(x)_v<=exp(a_v) quad (v in M_K^infinity) $
]

#proposition(title: "Ideal and Convex-Body Description")[
  Suppose $K$ is a number field. Define the fractional ideal

  $ I_D:=product_(v in M_K^0) frak(p)_v^(-n_v) $

  and the compact archimedean body

  $ R_D:={z in K_RR : norm(z_v)_v<=exp(a_v)
    " for every " v in M_K^infinity} $

  Under the Minkowski embedding,

  $ L(D)=I_D inter R_D $

  The ideal $I_D$ is the inverse of the fractional ideal represented by the
  finite part of $D$: a section is allowed a pole of order at most $n_v$, so
  it belongs locally to $frak(p)_v^(-n_v)$. In particular, $L(D)$ is finite.
]

#proof[
  Membership in $I_D$ is exactly the family of inequalities
  $v(x)>=-n_v$ at finite places. Membership in $R_D$ is exactly the family of
  archimedean inequalities. Thus the intersection is $L(D)$. The fractional
  ideal $I_D$ is a closed discrete lattice in $K_RR$, while $R_D$ is compact.
  Their intersection is finite.
]

#remark(title: "The Function-Field Case")[
  For a global function field $K=FF_q (C)$, the same definition gives the usual
  Riemann--Roch space

  $ L(D)={f in K | "div"(f)+D>=0} $

  It is a finite-dimensional $FF_q$-vector space and therefore a finite set.
  The number-field set $L(D)$ is likewise finite, but is generally not a vector
  space; the archimedean inequalities are convex rather than linear.
]

#proposition(title: "Translation by a Principal Divisor")[
  For $x in K^times$,

  $ L(D+"div"_"Ar" (x))=x^(-1)L(D) $

  Consequently, the cardinality of $L(D)$ depends only on the Arakelov divisor
  class of $D$.
]

#proof[
  For $y in K^times$,

  $ "div"_"Ar"(y)+D+"div"_"Ar"(x)>=0
    <=> "div"_"Ar"(x y)+D>=0 $

  which is precisely the asserted equality.
]

#proposition(title: "A Minkowski Nonvanishing Criterion")[
  Let $K$ be a number field of degree $n=r+2s$, and put

  $ B_K:=(2 slash pi)^s sqrt(abs(d_K)) $

  If $D in "Div"_"Ar"(K)$ satisfies

  $ exp(deg_"Ar" (D))>B_K $

  then $L(D)$ contains a nonzero element.
]

#proof[
  Write $D=sum n_v[v]+sum a_v[v]$. With the canonical Minkowski measure, each
  real inequality $abs(z_v)<=exp(a_v)$ contributes the interval length
  $2exp(a_v)$, while each complex inequality
  $abs(z_v)^2<=exp(a_v)$ contributes canonical area
  $2pi exp(a_v)$. Therefore

  $ mu_K (R_D)=2^r(2pi)^s exp(sum_(v|infinity) a_v) $

  Moreover,

  $ "N"(I_D)=product_(v in M_K^0) q_v^(-n_v) $

  and hence

  $ "covol"(I_D)="N"(I_D)sqrt(abs(d_K)) $

  It follows that

  $ mu_K (R_D) slash "covol"(I_D)
    =2^r(2pi)^s exp(deg_"Ar" (D)) slash sqrt(abs(d_K))
    =2^n exp(deg_"Ar" (D)) slash B_K
    >2^n $

  Minkowski's lattice point theorem gives a nonzero point of
  $I_D inter R_D=L(D)$.
]

#remark(title: [An Arithmetic Riemann--Roch Principle])[
  Large positive degree forces a nonzero global section. In a function field,
  Riemann--Roch expresses the eventual dimension of $L(D)$ as a linear
  function of $deg D$. In a number field, Minkowski theory supplies the
  analogous nonvanishing statement by comparing the volume of $R_D$ with the
  covolume of $I_D$.
]

== Unit Groups and the Logarithmic Lattice

We now specialize to a number field $K$ of signature $(r,s)$. The finite
places determine whether an element is a unit, while the infinite places
measure how large that unit is in each archimedean direction.

=== Units and Roots of Unity

#definition(title: "Unit Group")[
  The #emph[unit group] of $K$ is

  $ cal(O)_K^times
    ={u in K^times | v_frak(p) (u)=0
      " for every nonzero prime " frak(p) subset.eq cal(O)_K} $

  Equivalently, $u in cal(O)_K^times$ if and only if both $u$ and $u^(-1)$ are
  algebraic integers.
]

#proposition(title: "Norm Criterion for Units")[
  For $u in cal(O)_K$,

  $ u in cal(O)_K^times
    <=> "N"_(K slash QQ) (u)=plus.minus 1 $
]

#proof[
  If $u$ is a unit, multiplication by $u$ is an automorphism of the free
  $ZZ$-module $cal(O)_K$, so its determinant is a unit of $ZZ$. This
  determinant is the field norm.

  Conversely, let $m_u (X)$ be the monic minimal polynomial of $u$ over $QQ$.
  If $d=[QQ(u):QQ]$, then

  $ "N"_(K slash QQ)(u)
    ="N"_(QQ(u) slash QQ)(u)^([K:QQ(u)]) $

  The norm on the right is, up to sign, the constant term of $m_u$. Since it
  is an integer whose positive power has absolute value $1$, this constant
  term is $plus.minus 1$. Solving $m_u(u)=0$ for $u^(-1)$ expresses it as an
  integral polynomial in $u$, so $u^(-1) in cal(O)_K$.
]

#definition(title: "Roots of Unity")[
  Let

  $ mu_K:={zeta in K^times | zeta^m=1 " for some " m>=1} $

  be the group of roots of unity in $K$.
]

#proposition(title: "The Roots of Unity Form the Torsion Subgroup")[
  The group $mu_K$ is finite and is exactly the torsion subgroup of
  $cal(O)_K^times$. It is also the kernel of

  $ "div"_"Ar":K^times->"Div"_"Ar" (K) $
]

#proof[
  Every root of unity is integral, is a unit, and has modulus $1$ at every
  place. Hence $mu_K$ lies in all three groups under consideration.

  Conversely, an element of finite order in $K^times$ is a root of unity by
  definition. If $"div"_"Ar" (x)=0$, then $x$ is a unit and
  $norm(x)_v=1$ at every archimedean place, so $x in L(0)$. The set $L(0)$ is
  finite, and the kernel is a subgroup of this finite set. Thus every element
  of the kernel has finite order and belongs to $mu_K$.
]

#corollary(title: "The Fundamental Exact Sequence for Arakelov Divisors")[
  For every global field $K$, there is an exact sequence of abelian groups

  $ 1-->mu_K-->K^times-->^("div"_"Ar") "Div"_"Ar" (K)
    -->"Pic"_"Ar" (K)->0 $

  The first nontrivial kernel is $mu_K$, the image of the principal-divisor
  map is $"Princ"_"Ar" (K)$, and the final cokernel is the Arakelov Picard
  group by definition.
]

=== The Logarithmic Embedding

Put $ell:=r+s$, the number of archimedean places. The archimedean algebra is

$ K_RR^times tilde.eq (RR^times)^r times (CC^times)^s $

#definition(title: "Logarithmic Map")[
  The #emph[logarithmic map] is

  $ "Log":K_RR^times->RR^ell, quad
    (x_v)_(v|infinity) mapsto (log norm(x_v)_v)_(v|infinity) $

  For a diagonally embedded $x in K^times$, this is

  $ "Log"(x)=(log norm(x)_v)_(v|infinity) $

  Thus a real place contributes $log abs(sigma_v(x))$, while a complex place
  contributes $2log abs(sigma_v(x))$.
]

#proposition(title: "Norm as the Sum of Logarithmic Coordinates")[
  Let

  $ T:RR^ell->RR, quad T(y_1,dots,y_ell):=sum_(i=1)^ell y_i $

  For $x in K^times$,

  $ T("Log"(x))=log abs("N"_(K slash QQ) (x)) $
]

#proof[
  Each real embedding occurs once in the field norm and each complex-conjugate
  pair contributes $abs(sigma_v (x))^2$. Hence

  $ abs("N"_(K slash QQ) (x))=product_(v|infinity) norm(x)_v $

  Taking logarithms proves the formula.
]

#definition(title: "Trace-Zero Hyperplane and Unit Logarithm Lattice")[
  Define

  $ H_K:=ker(T)={y in RR^ell | sum_i y_i=0} $

  and

  $ Lambda_K:="Log"(cal(O)_K^times) $

  Since the norm of a unit has absolute value $1$,

  $ Lambda_K subset.eq H_K $

  The real vector space $H_K$ has dimension $ell-1=r+s-1$.
]

#proposition(title: "The Logarithmic Image Is Discrete")[
  The subgroup $Lambda_K subset.eq H_K$ is discrete, and

  $ ker("Log"|_(cal(O)_K^times))=mu_K $
]

#proof[
  The kernel statement follows from the preceding characterization of
  $mu_K$. To prove discreteness, let $C subset.eq H_K$ be compact. There is an
  $A>0$ such that every coordinate of every point of $C$ is at most $A$. If
  $"Log"(u) in C$, then $u in cal(O)_K$ and

  $ norm(u)_v<=exp(A) quad (v|infinity) $

  Thus $u$ lies in the finite Arakelov Riemann--Roch set attached to the
  divisor whose finite coefficients are zero and whose archimedean
  coefficients are all $A$. Only finitely many logarithmic vectors occur in
  $C$. In particular, $0$ is isolated in $Lambda_K$, so $Lambda_K$ is
  discrete.
]

#remark(title: "What Remains to Prove")[
  Discreteness gives only

  $ "rank" cal(O)_K^times<=r+s-1 $

  Dirichlet's theorem asserts equality. Geometrically, we must show that
  $Lambda_K$ spans the entire hyperplane $H_K$, or equivalently that it is
  cocompact there.
]

=== The Unit Lattice

#theorem(title: "The Unit Logarithms Form a Full Lattice")[
  The subgroup

  $ Lambda_K="Log"(cal(O)_K^times) $

  is a full lattice in $H_K$.
]

#proof[
  We already know that $Lambda_K$ is discrete. We prove cocompactness by
  showing that every point of $H_K$ lies within a fixed distance of
  $Lambda_K$.

  Choose a real number $B>max(1,B_K)$, where
  $B_K=(2 slash pi)^s sqrt(abs(d_K))$, and put

  $ b:=(log(B) slash ell,dots,log(B) slash ell) in RR^ell $

  Then every component of $b$ is nonnegative and $T(b)=log B$. There are only
  finitely many principal integral ideals of norm at most $B$. Choose one
  generator from each and call them $alpha_1,dots,alpha_m$. Put

  $ C:=max_(1<=j<=m) norm("Log"(alpha_j))_infinity $

  Now fix $h in H_K$. Let $D_h$ be the Arakelov divisor with zero finite part
  and archimedean coefficients $h_v+b_v$. Its degree is

  $ deg_"Ar" (D_h)=T(h+b)=log B>log B_K $

  The Minkowski nonvanishing criterion supplies a nonzero
  $gamma in L(D_h)$. Since the finite part of $D_h$ is zero,
  $gamma in cal(O)_K$. Put $g:="Log"(gamma)$. The defining inequalities for
  $L(D_h)$ say

  $ g_i<=h_i+b_i quad (1<=i<=ell) $

  Because $gamma$ is a nonzero algebraic integer,

  $ T(g)=log abs("N"_(K slash QQ) (gamma))>=0 $

  Set $w:=g-h$. Then $w_i<=b_i$ and $sum_i w_i=T(g)>=0$. For each $i$,

  $ w_i=T(g)-sum_(j!=i)w_j>=-sum_(j!=i)b_j>=-log B $

  Hence

  $ norm(g-h)_infinity<=log B $

  Summing the inequalities $g_i<=h_i+b_i$ also gives

  $ log abs("N"_(K slash QQ) (gamma))=T(g)<=log B $

  Thus the principal ideal $(gamma)$ has norm at most $B$, so
  $(gamma)=(alpha_j)$ for some $j$. The quotient

  $ u:=gamma slash alpha_j $

  is a unit. With $lambda:="Log"(u) in Lambda_K$, we have

  $ norm(h-lambda)_infinity
    <=norm(h-g)_infinity+norm("Log"(alpha_j))_infinity
    <=log B+C $

  The bound is independent of $h$. Therefore the quotient $H_K slash Lambda_K$
  is the continuous image of a fixed compact cube, hence is compact.
  The subgroup $Lambda_K$ is both discrete and cocompact, so it is a full
  lattice in $H_K$.
]

#quote[
  A unit may expand some archimedean directions and contract others, but its
  logarithmic vector has total sum zero. Dirichlet's theorem says that these
  balancing vectors fill the entire trace-zero hyperplane as a lattice.
]

#proposition(title: "Degree-Zero Arakelov Classes as a Torus over the Class Group")[
  There is a short exact sequence of topological abelian groups

  $ 0->H_K slash Lambda_K->"Pic"_"Ar"^0(K)
    ->"Cl"(cal(O)_K)->0 $

  The left-hand group is a compact real torus of dimension $r+s-1$, and the
  right-hand group is finite. Consequently,
  $"Pic"_"Ar"^0(K)$ is compact.
]

#proof[
  Send a degree-zero Arakelov divisor to the ideal class of its finite part.
  This is surjective: any fractional ideal can be supplied with
  archimedean coefficients whose sum makes the total degree zero.

  If the finite part is principal, subtracting a principal Arakelov divisor
  leaves a pure archimedean divisor of degree zero, hence a vector in $H_K$.
  Two such vectors determine the same Arakelov class exactly when their
  difference is the logarithmic vector of a unit. The kernel is therefore
  $H_K slash Lambda_K$. The unit-lattice theorem makes this quotient a compact
  torus, and the class-number theorem makes the final quotient finite.
]

== The Regulator and Dirichlet's Unit Theorem

The class number counts the discrete ideal-class obstruction. The regulator
measures the continuous archimedean size of the unit lattice.

=== The Regulator

Let $ell=r+s$. For $1<=k<=ell$, let

$ pi_k:H_K->RR^(ell-1) $

be the isomorphism obtained by deleting the $k$-th coordinate.

#definition(title: "Regulator")[
  The #emph[regulator] of $K$ is

  $ R_K:="covol"(pi_k (Lambda_K)) $

  with respect to ordinary Lebesgue measure on $RR^(ell-1)$. If $ell=1$, we
  use the zero-dimensional convention $R_K=1$.
]

#proposition(title: "Determinant Formula and Independence of the Deleted Coordinate")[
  Let $epsilon_1,dots,epsilon_(ell-1)$ be units whose logarithmic vectors form
  a $ZZ$-basis of $Lambda_K$, and form the matrix

  $ A=(log norm(epsilon_j)_(v_i))_(1<=i<=ell,1<=j<=ell-1) $

  Delete any row $k$ to obtain the square matrix $A_k$. Then

  $ R_K=abs(det A_k) $

  and this value is independent of $k$.
]

#proof[
  The determinant formula for covolume gives the first equality. Every column
  of $A$ lies in $H_K$, so its entries sum to zero. The signed maximal minors
  of $A$ form a vector in the one-dimensional kernel of $A^T$; this kernel
  is spanned by $(1,dots,1)$. Hence the determinants $det A_k$ agree up to
  sign, and their absolute values are equal.
]

#remark(title: "Geometric Meaning of the Regulator")[
  The regulator is the volume of one fundamental cell of the logarithmic unit
  lattice. A small regulator means that units occur densely in the
  archimedean hyperplane; a large regulator means that fundamental units must
  travel far before returning to an equivalent logarithmic position.
]

#example(title: "Real Quadratic Fields")[
  Let $K$ be real quadratic and let $epsilon>1$ be a fundamental unit. The two
  real logarithmic coordinates satisfy

  $ "Log"(epsilon)=(log epsilon,-log epsilon) $

  after choosing the identity embedding first. Therefore

  $ R_K=log epsilon $

  For example, the fundamental unit of $QQ(sqrt(2))$ is
  $epsilon=1+sqrt(2)$, and

  $ R_(QQ(sqrt(2)))=log(1+sqrt(2)) $
]

#remark(title: "Pell Equations")[
  In a real quadratic field, finding a fundamental unit is equivalent to
  finding a smallest positive solution of an appropriate Pell equation. The
  regulator is the logarithmic size of this solution. This explains why
  regulators may be unexpectedly large even for fields with modest
  discriminant.
]

=== Dirichlet's Unit Theorem

#theorem(title: "Dirichlet's Unit Theorem")[
  Let $K$ be a number field with $r$ real places and $s$ complex places. Then

  $ cal(O)_K^times tilde.eq mu_K times ZZ^(r+s-1) $

  In particular, the unit group is finitely generated, its torsion subgroup is
  $mu_K$, and its free rank is $r+s-1$.
]

#proof[
  For a number field, the logarithmic map gives an exact sequence

  $ 1->mu_K->cal(O)_K^times->Lambda_K->0 $

  The unit-lattice theorem identifies $Lambda_K$ with a full lattice in the
  $(r+s-1)$-dimensional vector space $H_K$. Hence

  Since every full lattice in a real vector space of dimension $r+s-1$ is a
  free abelian group of that rank,

  $ Lambda_K tilde.eq ZZ^(r+s-1) $

  The group $Lambda_K$ is free and therefore projective, so the exact
  sequence splits. This proves

  $ cal(O)_K^times tilde.eq mu_K times ZZ^(r+s-1) $

  and completes the proof.
]

#corollary(title: "The Unit Theorem for Global Fields")[
  Let $K slash F$ be a finite separable extension, where $F=QQ$ or
  $F=FF_q (t)$. In the function-field case, take $FF_q$ to be the full constant
  field of $K$ and $t$ to be a separating element. Let $S$ be the places of
  $K$ above the distinguished infinite place of $F$, and define the group of
  #emph[$S$-units] by

  $ cal(O)_(K,S)^times
    :={x in K^times | v(x)=0 " for every " v in.not S} $

  Then

  $ cal(O)_(K,S)^times tilde.eq mu_K times ZZ^(abs(S)-1) $
]

#proof[
  For $F=QQ$, the set $S$ consists of the $r+s$ archimedean places, and
  $cal(O)_(K,S)^times=cal(O)_K^times$. The result is Dirichlet's unit theorem.

  For a global function field, let $C slash FF_q$ be the smooth projective
  curve with function field $K$. The divisor of an $S$-unit is supported on
  $S$. Put

  $ "Div"_S^0(K)
    :={sum_(v in S) n_v [v] | sum_(v in S) n_v deg(v)=0} $

  The principal-divisor map gives an exact sequence

  $ 1->FF_q^times->cal(O)_(K,S)^times
    ->"Div"_S^0(K) $

  The quotient of $"Div"_S^0(K)$ by the image injects into the finite
  degree-zero divisor class group of $C$. Thus the image has finite index in
  the free abelian group $"Div"_S^0(K)$, whose rank is $abs(S)-1$. The image
  has the same rank, and the exact sequence with this image as its final term
  splits because the image is free. Finally, $mu_K=FF_q^times$ because
  $FF_q$ is the full constant field. This proves the function-field case.
]

#remark(title: "The Function-Field Ring Depends on Infinity")[
  Unlike $QQ$, the rational function field has many places that can be moved
  to infinity by a change of variable. Changing the chosen separating element
  $t$ can therefore change $S$, the ring $cal(O)_(K,S)$, and even the rank
  $abs(S)-1$. The theorem is intrinsic to the pair $(K,S)$, not merely to the
  abstract function field $K$.
]
